version: '3'
services:
  redis-server:
    image: redis:alpine
    restart: always

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: disblock


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  disblock:
    depends_on:
      - redis-server
      - db
    image: disblock
    ports:
      - 8081:8081
    restart: always

volumes:
  db_data: {}