version: '3'


services:
  redis-server:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data


#https://hub.docker.com/_/postgres/?tab=description
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  #Web panel
  disblock:
    depends_on:
      - redis-server
      - db
    image: disblock
    ports:
      - 8081:8081
      - 80:80
      - 443:443
    restart: always
    environment:
      #Values are stored in .env file
      PGHOST: ${DB_HOST}
      PGPASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_USER}
      PGDATABASE: ${DB_DATABASE}
      PGPORT: ${DB_PORT}
      NODE_ENV: ${NODE_ENV}
      DEBUG: ${DEBUG}
      LOGS_MAX_FILES: ${LOGS_MAX_FILES}
      HTTPS: ${HTTPS}
      LOGIN_URL: ${LOGIN_URL}
    volumes:
      - disblock_logs:/node/logs
      - ./certs/:/node/certs/:ro
      #The host /cert/ folder is sent in docker image, in folder /node/cert/.
      #:ro = Read Only

  #Discord bot
  disbot:
    depends_on:
      - db
    image: disbot
    restart: always
    volumes:
      - disbot_logs:/node/logs
    environment:
      PGHOST: ${DB_HOST}
      PGPASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_USER}
      PGDATABASE: ${DB_DATABASE}
      PGPORT: ${DB_PORT}
      TOKEN: ${BOT_TOKEN}
      LOGS_MAX_FILES: ${LOGS_MAX_FILES}
      DEBUG: ${DEBUG}
      NODE_ENV: ${NODE_ENV}


volumes:
  db_data: {}
  disblock_logs: {}
  disbot_logs: {}
  redis_data: {}
